---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-app-service
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "app.selectorLabels" . | nindent 4 }}
  ports:
    - port: 80
      targetPort: 8080